### ISSUE TITLE
New download host

### ISSUE THREAD

**Issue by joerki16** [JuanJakobo/Pocketbook-Die-Zeit#2]
Thanks for the great downloader. I use it every week. Die Zeit changed their host. So if there is time to implement:

The new download host is: https://media-delivery.zeit.de/xyz.epub

**Comment by JuanJakobo** [comment]
Hey, it seems they also changed something regarding the login mechanism. I will have a look into it.

**Comment by JuanJakobo** [comment]
Hey, I just had a try and it seems as if they changed quite some logic. I just set premium.zeit.de as starting page for the webbrowser and download the current edition from there.
